import json

# 手工翻译字典 - 剩余的键值对
translations = {
    "indexing.chunks": "个块",
    "indexing.localModel": "嵌入模型",
    "indexing.localModel.mini": "快速（约 23 MB）",
    "indexing.localModel.base": "平衡（约 278 MB）",
    "indexing.localModel.large": "高质量（约 562 MB）",
    "indexing.localModel.miniDescription": "轻量级模型，快速索引。基础多语言支持。",
    "indexing.localModel.baseDescription": "更好的质量，良好的多语言搜索。首次使用时下载（约 278 MB）。",
    "indexing.localModel.largeDescription": "最佳质量，优秀的多语言搜索。首次使用时下载（约 562 MB）。",
    "indexing.localModel.reindexWarning": "更改模型将重新下载并重新索引整个代码库。",
    "browser.checkingConnection": "检查连接中...",
    "browser.connectionCheck": "连接检查",
    "browser.connectionSuccessful": "连接成功",
    "browser.connectionFailed": "连接失败",
    "browser.retrying": "重试中...",
    "browser.maxRetriesReached": "达到最大重试次数",
    "browser.browserReady": "浏览器已就绪",
    "apiConfig.provider": "提供商",
    "apiConfig.modelId.placeholder": "输入模型 ID",
    "apiConfig.modelId.label": "模型 ID",
    "apiConfig.apiKey.placeholder": "输入 API 密钥（可选）",
    "apiConfig.apiKey.label": "API 密钥",
    "apiConfig.baseURL.placeholder": "输入基础 URL（可选）",
    "apiConfig.baseURL.label": "基础 URL",
    "apiConfig.addProvider": "添加自定义提供商",
    "apiConfig.useProvider": "使用此提供商",
    "apiConfig.removeProvider": "删除",
    "apiConfig.testConnection": "测试连接",
    "apiConfig.testingConnection": "测试中...",
    "apiConfig.connectionSuccessful": "连接成功",
    "apiConfig.connectionFailed": "连接失败",
    "about.version": "版本",
    "about.build": "构建",
    "about.electron": "Electron",
    "about.chrome": "Chrome",
    "about.nodejs": "Node.js",
    "about.v8": "V8",
    "about.os": "操作系统",
    "about.memoryUsage": "内存使用",
    "about.releaseNotes": "发行说明",
    "about.documentation": "文档",
    "about.reportIssue": "报告问题",
    "about.viewLicense": "查看许可证",
    "about.checkForUpdates": "检查更新",
    "about.upToDate": "已是最新版本",
    "about.updateAvailable": "有可用更新",
    "about.downloading": "下载中...",
    "about.readyToInstall": "准备安装",
    "about.installUpdate": "安装更新",
    "debug.clearHistory": "清除历史",
    "debug.clearHistoryConfirm": "确定要清除所有聊天历史吗？",
    "debug.yes": "是",
    "debug.no": "否",
    "debug.historyCleared": "历史已清除",
    "debug.exportLogs": "导出日志",
    "debug.logsExported": "日志已导出",
    "debug.restartExtension": "重启扩展",
    "debug.extensionRestarted": "扩展已重启",
    "history.search": "搜索历史...",
    "history.noResults": "无结果",
    "history.delete": "删除",
    "history.deleteConfirm": "确定要删除此会话吗？",
    "history.export": "导出",
    "history.exported": "已导出",
    "preferredLanguage.label": "AI 响应语言",
    "preferredLanguage.description": "控制 AI 模型在响应中使用的语言。独立于上面的界面语言。",
    "preferredLanguage.alwaysThink": "始终使用此语言思考",
    "preferredLanguage.alwaysThinkDescription": "强制模型使用选定的语言进行内部推理（思维链）。这可能提高您母语的推理质量，但可能会降低某些模型的整体性能。",
    "mcp.title": "MCP 服务器",
    "mcp.description": "模型上下文协议（MCP）允许 ShunCode 连接到外部工具和数据源。",
    "mcp.noServers": "未配置 MCP 服务器",
    "mcp.addServer": "添加服务器",
    "mcp.serverName": "服务器名称",
    "mcp.serverCommand": "命令",
    "mcp.serverArgs": "参数",
    "mcp.serverEnv": "环境变量",
    "mcp.serverEnabled": "已启用",
    "mcp.serverDisabled": "已禁用",
    "mcp.enable": "启用",
    "mcp.disable": "禁用",
    "mcp.edit": "编辑",
    "mcp.delete": "删除",
    "mcp.deleteConfirm": "确定要删除此 MCP 服务器吗？",
    "mcp.tools": "个工具",
    "mcp.resources": "个资源",
    "mcp.prompts": "个提示",
    "mcp.connecting": "连接中...",
    "mcp.connected": "已连接",
    "mcp.disconnected": "未连接",
    "mcp.error": "错误",
    "fastContext.title": "Fast Context",
    "fastContext.description": "Fast Context 是一个专用子代理，使用 AI 模型进行快速代码检索。",
    "fastContext.enabled": "已启用",
    "fastContext.disabled": "已禁用",
    "fastContext.enable": "启用 Fast Context",
    "fastContext.apiUrl": "API URL",
    "fastContext.apiKey": "API 密钥",
    "fastContext.modelId": "模型 ID",
    "fastContext.maxTurns": "最大轮次",
    "fastContext.maxParallelCalls": "最大并行调用数",
    "fastContext.timeoutSeconds": "超时（秒）",
    "fastContext.systemPrompt": "系统提示词",
    "fastContext.excludePatterns": "排除模式",
    "fastContext.maxReadFileSize": "最大读取文件大小",
    "fastContext.showProgress": "显示进度",
    "error.generic": "发生错误",
    "error.apiKeyMissing": "缺少 API 密钥",
    "error.modelNotFound": "未找到模型",
    "error.networkError": "网络错误",
    "error.timeout": "请求超时",
    "error.rateLimitExceeded": "超出速率限制",
    "error.invalidRequest": "无效请求",
    "error.serverError": "服务器错误",
    "error.unknownError": "未知错误",
    "button.ok": "确定",
    "button.cancel": "取消",
    "button.save": "保存",
    "button.delete": "删除",
    "button.edit": "编辑",
    "button.add": "添加",
    "button.remove": "移除",
    "button.close": "关闭",
    "button.back": "返回",
    "button.next": "下一步",
    "button.finish": "完成",
    "button.yes": "是",
    "button.no": "否",
    "button.retry": "重试",
    "button.continue": "继续",
    "button.skip": "跳过",
    "common.loading": "加载中...",
    "common.saving": "保存中...",
    "common.saved": "已保存",
    "common.error": "错误",
    "common.success": "成功",
    "common.warning": "警告",
    "common.info": "信息",
    "common.optional": "可选",
    "common.required": "必填",
    "common.none": "无",
    "common.all": "全部",
    "common.search": "搜索",
    "common.filter": "筛选",
    "common.sort": "排序",
    "common.refresh": "刷新",
    "common.clear": "清除",
    "common.reset": "重置",
    "common.default": "默认",
    "common.custom": "自定义",
    "common.enabled": "已启用",
    "common.disabled": "已禁用"
}

# 读取英文文件
with open('webview-ui/src/i18n/locales/en.json', 'r', encoding='utf-8') as f:
    en_data = json.load(f)

# 读取当前的中文文件
with open('webview-ui/src/i18n/locales/zh-CN.json', 'r', encoding='utf-8') as f:
    zh_data = json.load(f)

# 合并翻译
for key, value in en_data.items():
    if key not in zh_data or zh_data[key] == value:  # 如果还没翻译或还是英文
        if key in translations:
            zh_data[key] = translations[key]
        else:
            # 保持英文（或者你可以添加更多翻译）
            zh_data[key] = value

# 写入中文文件
with open('webview-ui/src/i18n/locales/zh-CN.json', 'w', encoding='utf-8') as f:
    json.dump(zh_data, f, ensure_ascii=False, indent='\t')

print(f"翻译完成！共 {len(zh_data)} 个键")
